name: flap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.0
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar_placeholder.png
    - assets/models/Ari_Baddie_3.glb
    - assets/images/intro_bg.jpg
    - assets/audio/intro_music.mp3
